events {
    worker_connections 1024;
}

http {
    upstream gate_parkir {
        server gate-utama:5000;
        server gate-ekspres:5000;
        server gate-khusus:5000;
    }

    server {
        listen 80;
        server_name localhost;

        location / {
            proxy_pass http://gate_parkir;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_http_version 1.1;
            proxy_set_header Connection "";
        }
    }
}
